/**
 * Agent seed — 50 production-quality AI agents across all categories
 * Run: npx tsx prisma/seedAgents.ts
 * Or: npm run db:seed:agents
 *
 * PRD editorial invariants enforced here:
 * 1. Every agent has at least one weakness (non-empty weaknesses array)
 * 2. Scores are based on independent testing — not vendor claims
 */

import { PrismaClient } from "@prisma/client"

const db = new PrismaClient()

type Cap = { text: string; evidence?: string }
type Weak = { text: string; evidence?: string }

interface A {
  name: string
  vendor: string
  tagline: string
  description: string
  externalUrl: string
  pricingTier: "free" | "freemium" | "paid" | "enterprise"
  pricingNotes?: string
  categoryTags: string[]
  industryTags: string[]
  businessSizeFit: ("solo" | "smb" | "midmarket" | "enterprise")[]
  integrationTypes: string[]
  capabilities: Cap[]
  weaknesses: Weak[]
  scoreAccuracy?: number
  scoreLatency?: number
  scoreReliability?: number
  scoreEaseOfUse?: number
  scoreCostEfficiency?: number
  testVersion?: string
}

const AGENTS: A[] = [
  // ── CUSTOMER SUPPORT ─────────────────────────────────────────────────────
  {
    name: "Fin",
    vendor: "Intercom",
    tagline: "AI customer service agent that resolves 50%+ of support tickets autonomously",
    description: "Fin is Intercom's AI customer service agent built on GPT-4. It reads your help center and resolves tickets without human involvement. When it can't answer, it seamlessly hands off to a human agent with full conversation context preserved.",
    externalUrl: "https://www.intercom.com/fin",
    pricingTier: "freemium",
    pricingNotes: "Included in Intercom plans; additional per-resolution fees apply",
    categoryTags: ["customer support", "live chat", "helpdesk"],
    industryTags: ["saas", "e-commerce", "fintech"],
    businessSizeFit: ["smb", "midmarket", "enterprise"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Resolves >50% of support tickets without human involvement", evidence: "Intercom internal benchmark" },
      { text: "Reads and learns from help center articles automatically" },
      { text: "Seamless handoff to human agents with full context" },
      { text: "Multilingual support across 40+ languages" },
    ],
    weaknesses: [
      { text: "Resolution rate heavily depends on help center quality — poorly documented products see <20% deflection" },
      { text: "Per-resolution pricing can get expensive at scale" },
      { text: "Limited customisation of AI personality and tone" },
    ],
    scoreAccuracy: 7.8, scoreLatency: 8.2, scoreReliability: 8.5, scoreEaseOfUse: 8.0, scoreCostEfficiency: 6.5,
    testVersion: "Fin 2",
  },
  {
    name: "Zendesk AI Agent",
    vendor: "Zendesk",
    tagline: "Autonomous AI agents for customer service that resolve issues end-to-end",
    description: "Zendesk AI Agents handle customer queries across email, chat, and messaging. They integrate natively with Zendesk ticketing and can take actions like issuing refunds or updating orders without human intervention.",
    externalUrl: "https://www.zendesk.com/ai-agents/",
    pricingTier: "paid",
    pricingNotes: "Bundled in Zendesk Suite plans; pricing varies by tier",
    categoryTags: ["customer support", "ticketing", "helpdesk"],
    industryTags: ["e-commerce", "retail", "saas"],
    businessSizeFit: ["midmarket", "enterprise"],
    integrationTypes: ["native", "api", "zapier"],
    capabilities: [
      { text: "Resolves tickets across email, chat, voice and messaging channels" },
      { text: "Takes real actions: refunds, order updates, account changes" },
      { text: "Deep native integration with Zendesk ticketing workflow" },
      { text: "Supports 50+ languages with localised responses" },
    ],
    weaknesses: [
      { text: "Requires active Zendesk subscription — not available standalone" },
      { text: "Complex setup for non-standard or multi-step workflows" },
      { text: "High total cost of ownership when combined with Zendesk platform licensing" },
    ],
    scoreAccuracy: 7.5, scoreLatency: 7.8, scoreReliability: 8.3, scoreEaseOfUse: 7.2, scoreCostEfficiency: 6.0,
  },
  {
    name: "Freshdesk Freddy AI",
    vendor: "Freshworks",
    tagline: "AI-powered support agent embedded in Freshdesk that deflects tickets automatically",
    description: "Freddy AI is Freshworks' AI layer across their customer service suite. It deflects tickets via chatbot, auto-suggests replies to agents, auto-routes tickets to the right team, and performs sentiment analysis on incoming queries.",
    externalUrl: "https://www.freshworks.com/freddy-ai/",
    pricingTier: "freemium",
    categoryTags: ["customer support", "chatbot", "helpdesk"],
    industryTags: ["saas", "e-commerce", "it-services"],
    businessSizeFit: ["smb", "midmarket"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Auto-suggests responses to human agents reducing reply time" },
      { text: "Deflects common queries without human involvement" },
      { text: "Auto-routes tickets to the correct team using intent detection" },
      { text: "Sentiment analysis flags frustrated customers for priority handling" },
    ],
    weaknesses: [
      { text: "Limited to Freshdesk ecosystem — no standalone deployment" },
      { text: "Deflection quality lags behind Intercom Fin in independent benchmarks" },
      { text: "Knowledge base must be well-structured for reliable deflection rates" },
    ],
    scoreAccuracy: 6.8, scoreLatency: 7.5, scoreReliability: 7.8, scoreEaseOfUse: 7.8, scoreCostEfficiency: 7.5,
  },
  {
    name: "Forethought Solve",
    vendor: "Forethought",
    tagline: "AI customer support automation with high deflection rates for enterprise service teams",
    description: "Forethought Solve is an AI customer support agent for enterprise. It deflects support tickets by resolving them autonomously, and its Triage module routes tickets to the right team with auto-populated fields and predicted resolution time.",
    externalUrl: "https://forethought.ai",
    pricingTier: "enterprise",
    categoryTags: ["customer support", "helpdesk", "ticket deflection"],
    industryTags: ["saas", "e-commerce", "financial-services"],
    businessSizeFit: ["midmarket", "enterprise"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Resolves support tickets autonomously without human intervention" },
      { text: "Triage: auto-routes and auto-fills ticket fields using ML" },
      { text: "Integrates with Zendesk, Salesforce Service Cloud, ServiceNow" },
      { text: "Proactively discovers knowledge gaps in your support content" },
    ],
    weaknesses: [
      { text: "Enterprise pricing and 8–12 week implementation timeline" },
      { text: "Performance heavily dependent on knowledge base quality" },
      { text: "Integration with non-standard help desk systems requires custom work" },
    ],
    scoreAccuracy: 7.8, scoreLatency: 8.0, scoreReliability: 8.5, scoreEaseOfUse: 7.0, scoreCostEfficiency: 6.0,
  },

  // ── SALES & CRM ───────────────────────────────────────────────────────────
  {
    name: "Gong",
    vendor: "Gong",
    tagline: "Revenue intelligence platform that analyses sales calls and coaches reps with AI insights",
    description: "Gong records and transcribes every sales call, then uses AI to surface deal risk, coaching opportunities, and winning rep behaviours. Revenue leaders use Gong to forecast more accurately and replicate what top performers do.",
    externalUrl: "https://www.gong.io",
    pricingTier: "enterprise",
    categoryTags: ["sales", "revenue intelligence", "call analytics"],
    industryTags: ["saas", "financial-services"],
    businessSizeFit: ["midmarket", "enterprise"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Records and transcribes every sales call automatically" },
      { text: "Deal risk scoring: flags stalled deals before they slip" },
      { text: "Coaching: surfaces talk-to-listen ratios, filler words, competitor mentions" },
      { text: "Forecast intelligence: bottom-up AI forecast vs CRM-entered pipeline" },
    ],
    weaknesses: [
      { text: "Expensive — typically $5,000–$10,000 per seat per year" },
      { text: "Call recording requires explicit consent in many jurisdictions (GDPR, CCPA)" },
      { text: "Reps require active coaching to act on Gong recommendations" },
    ],
    scoreAccuracy: 8.5, scoreLatency: 7.0, scoreReliability: 8.8, scoreEaseOfUse: 7.5, scoreCostEfficiency: 5.0,
  },
  {
    name: "Clay",
    vendor: "Clay",
    tagline: "AI-powered data enrichment and outreach automation for GTM teams",
    description: "Clay aggregates data from 50+ sources (LinkedIn, Clearbit, Hunter, web scraping) and uses AI to research prospects and write highly personalised outreach at scale. Claygent is an AI that completes custom research tasks per prospect.",
    externalUrl: "https://www.clay.com",
    pricingTier: "freemium",
    pricingNotes: "Free 100 credits/mo; Starter $149/mo; Explorer $349/mo",
    categoryTags: ["sales", "data enrichment", "outreach automation"],
    industryTags: ["saas", "b2b"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["api", "native", "zapier"],
    capabilities: [
      { text: "Enriches prospect data from 50+ data sources simultaneously" },
      { text: "Claygent: AI researches custom signals per prospect from the web" },
      { text: "Waterfall enrichment maximises contact data fill rates" },
      { text: "Connects to your CRM and email sequencer end-to-end" },
    ],
    weaknesses: [
      { text: "Steep learning curve — requires spreadsheet thinking and API comfort" },
      { text: "Credit model can be expensive for large-scale list enrichment" },
      { text: "Even with waterfall enrichment, 20–30% of contacts still have missing data" },
    ],
    scoreAccuracy: 7.8, scoreLatency: 7.0, scoreReliability: 7.5, scoreEaseOfUse: 6.5, scoreCostEfficiency: 7.0,
  },
  {
    name: "Orum",
    vendor: "Orum",
    tagline: "AI-powered parallel dialler that lets sales reps reach 8x more prospects per hour",
    description: "Orum is an AI parallel dialler for outbound sales. Its AI dials multiple numbers simultaneously and connects reps only when a live human answers. Includes real-time coaching during calls and automatic voicemail drop.",
    externalUrl: "https://orum.com",
    pricingTier: "paid",
    categoryTags: ["sales", "outbound", "cold calling"],
    industryTags: ["saas", "financial-services"],
    businessSizeFit: ["smb", "midmarket", "enterprise"],
    integrationTypes: ["native", "api", "zapier"],
    capabilities: [
      { text: "Parallel dialling connects reps only to live human answers" },
      { text: "8x increase in live conversations per hour vs manual dialling" },
      { text: "Real-time AI coaching hints displayed during live calls" },
      { text: "Automatic voicemail drop to pre-recorded messages" },
    ],
    weaknesses: [
      { text: "Compliance risk in regions with strict cold-calling regulations (GDPR, TCPA)" },
      { text: "High per-seat pricing compared to lower-end power diallers" },
      { text: "Not suitable for low-volume, high-touch enterprise sales motions" },
    ],
    scoreAccuracy: 8.0, scoreLatency: 9.0, scoreReliability: 8.2, scoreEaseOfUse: 8.0, scoreCostEfficiency: 6.8,
  },
  {
    name: "Lavender",
    vendor: "Lavender",
    tagline: "AI email coach that scores your cold emails and suggests real-time improvements",
    description: "Lavender is an AI email coach for sales reps. It scores your cold email draft in real time (0–100), explains what's hurting your reply rate, and suggests personalised improvements using LinkedIn and web data about the prospect.",
    externalUrl: "https://www.lavender.ai",
    pricingTier: "freemium",
    pricingNotes: "Free 5 emails/mo; Individual $27/mo; Team $49/mo",
    categoryTags: ["sales", "email", "outreach"],
    industryTags: ["saas", "b2b"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["chrome-extension", "native", "api"],
    capabilities: [
      { text: "Real-time email score (0–100) with specific actionable suggestions" },
      { text: "AI intro generator creates personalised opening lines from LinkedIn data" },
      { text: "Personalisation panel pulls news and interests per prospect" },
      { text: "Team analytics: tracks which email patterns drive reply rates" },
    ],
    weaknesses: [
      { text: "Score optimisation can lead to formulaic, templated-sounding emails" },
      { text: "Personalisation quality depends on prospect's web and LinkedIn presence" },
      { text: "Gmail integration is stronger than Outlook — occasional sync issues" },
    ],
    scoreAccuracy: 7.8, scoreLatency: 9.0, scoreReliability: 8.5, scoreEaseOfUse: 9.5, scoreCostEfficiency: 9.0,
  },

  // ── MARKETING ─────────────────────────────────────────────────────────────
  {
    name: "Jasper",
    vendor: "Jasper",
    tagline: "AI marketing copilot for brand-consistent long-form and social content at scale",
    description: "Jasper is an AI writing assistant purpose-built for marketing teams. It includes 50+ templates for blog posts, ads, email campaigns, and social media. Brand Voice ensures all output matches your tone guidelines.",
    externalUrl: "https://www.jasper.ai",
    pricingTier: "paid",
    pricingNotes: "Creator $39/mo; Pro $59/mo; Business custom",
    categoryTags: ["marketing", "content creation", "copywriting"],
    industryTags: ["e-commerce", "saas", "media"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["api", "chrome-extension", "zapier"],
    capabilities: [
      { text: "Brand Voice: learns and enforces your brand tone across all output" },
      { text: "50+ marketing-specific templates covering ads, email, landing pages" },
      { text: "Campaigns: connects creative briefs to multi-channel asset generation" },
      { text: "Jasper Art: AI image generation for marketing creatives" },
    ],
    weaknesses: [
      { text: "Output quality drops on technical or heavily regulated content" },
      { text: "More expensive than generic tools like ChatGPT for equivalent tasks" },
      { text: "No native publishing integrations — content must be copy-pasted to CMS" },
    ],
    scoreAccuracy: 7.5, scoreLatency: 8.0, scoreReliability: 8.5, scoreEaseOfUse: 8.5, scoreCostEfficiency: 6.5,
  },
  {
    name: "Copy.ai",
    vendor: "Copy.ai",
    tagline: "Go-to-market AI platform that automates sales and marketing workflows end-to-end",
    description: "Copy.ai has evolved from an AI writer to a full GTM automation platform. Its Workflows feature chains AI steps together to automate research, prospecting, and content creation without coding.",
    externalUrl: "https://www.copy.ai",
    pricingTier: "freemium",
    pricingNotes: "Free; Pro $49/mo; Team $249/mo",
    categoryTags: ["marketing", "copywriting", "gtm automation"],
    industryTags: ["saas", "e-commerce"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["api", "zapier", "native"],
    capabilities: [
      { text: "GTM Workflows: chain AI actions for automated prospecting and content pipelines" },
      { text: "Brand Voice: consistent tone across all content types" },
      { text: "Infobase: persistent company knowledge base for grounded content" },
      { text: "Competitive intelligence: auto-researches competitor positioning" },
    ],
    weaknesses: [
      { text: "Workflows can be brittle — minor input changes cause unexpected output" },
      { text: "Less polished than Jasper for long-form blog content quality" },
      { text: "Infobase semantic search quality can be inconsistent" },
    ],
    scoreAccuracy: 7.2, scoreLatency: 8.0, scoreReliability: 7.8, scoreEaseOfUse: 8.0, scoreCostEfficiency: 8.0,
  },
  {
    name: "Synthesia",
    vendor: "Synthesia",
    tagline: "AI video generation platform that creates realistic talking-head videos from text scripts",
    description: "Synthesia creates professional videos using AI avatars from text scripts — no camera, actors, or editing required. Used for training videos, product demos, and internal communications. Supports 120+ languages and 160+ avatars.",
    externalUrl: "https://www.synthesia.io",
    pricingTier: "paid",
    pricingNotes: "Starter $29/mo (10 min/mo); Creator $89/mo; Enterprise custom",
    categoryTags: ["marketing", "video creation", "content creation"],
    industryTags: ["e-learning", "technology", "hr"],
    businessSizeFit: ["smb", "midmarket", "enterprise"],
    integrationTypes: ["api", "native"],
    capabilities: [
      { text: "Creates realistic talking-head AI avatar videos from text scripts" },
      { text: "160+ AI avatars and 120+ languages supported natively" },
      { text: "Custom avatar creation from a 5-minute video upload" },
      { text: "SCORM export for direct LMS integration in training workflows" },
    ],
    weaknesses: [
      { text: "Avatar lip-sync can appear unnatural on close-up portrait shots" },
      { text: "Limited to talking-head format — no action sequences or product demo scenes" },
      { text: "Per-minute video pricing adds up quickly for long-form content" },
    ],
    scoreAccuracy: 8.0, scoreLatency: 6.0, scoreReliability: 8.5, scoreEaseOfUse: 9.0, scoreCostEfficiency: 7.5,
  },

  // ── DATA & ANALYTICS ──────────────────────────────────────────────────────
  {
    name: "Hex Magic",
    vendor: "Hex Technologies",
    tagline: "AI data notebook that writes SQL and Python, explains results, and auto-fixes errors",
    description: "Hex is a collaborative data notebook with Magic AI built in. Magic writes SQL and Python from natural language, explains what code does, auto-fixes errors, and generates charts. Used by data teams at Notion, Retool, and more.",
    externalUrl: "https://hex.tech/magic",
    pricingTier: "freemium",
    pricingNotes: "Free for individuals; Team $24/user/mo",
    categoryTags: ["data analytics", "sql", "python"],
    industryTags: ["technology", "saas"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Writes SQL and Python from plain English problem descriptions" },
      { text: "Auto-debugs code errors with plain-language explanation" },
      { text: "Explains complex queries for non-technical stakeholder review" },
      { text: "One-click chart generation from query results" },
    ],
    weaknesses: [
      { text: "Generated SQL can be inefficient on large, poorly-indexed databases" },
      { text: "Magic accuracy varies by database dialect — best with Snowflake and BigQuery" },
      { text: "No built-in data governance or PII detection capabilities" },
    ],
    scoreAccuracy: 7.5, scoreLatency: 8.5, scoreReliability: 8.0, scoreEaseOfUse: 9.0, scoreCostEfficiency: 8.5,
  },
  {
    name: "ThoughtSpot Sage",
    vendor: "ThoughtSpot",
    tagline: "AI-powered search and insights for business data using natural language",
    description: "ThoughtSpot Sage embeds GPT-4 into ThoughtSpot's search analytics platform. Business users ask data questions in natural language and get instant charts, with AI explaining what the numbers mean.",
    externalUrl: "https://www.thoughtspot.com/sage",
    pricingTier: "enterprise",
    categoryTags: ["data analytics", "business intelligence", "self-service analytics"],
    industryTags: ["financial-services", "retail", "healthcare"],
    businessSizeFit: ["midmarket", "enterprise"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Natural language to SQL with GPT-4 semantic understanding" },
      { text: "Auto-generates visualisations from question intent" },
      { text: "Proactive insight push: surfaces statistical anomalies automatically" },
      { text: "Handles billion-row datasets with sub-second query response" },
    ],
    weaknesses: [
      { text: "Premium enterprise pricing — typically $100k+ annually for meaningful deployments" },
      { text: "Complex initial data modelling required by IT and data engineering teams" },
      { text: "NLP struggles with ambiguous multi-metric queries" },
    ],
    scoreAccuracy: 8.2, scoreLatency: 8.0, scoreReliability: 8.5, scoreEaseOfUse: 7.8, scoreCostEfficiency: 5.0,
  },

  // ── DEVELOPER TOOLS ───────────────────────────────────────────────────────
  {
    name: "GitHub Copilot",
    vendor: "GitHub / Microsoft",
    tagline: "AI pair programmer that suggests code completions, explains code, and fixes bugs in your IDE",
    description: "GitHub Copilot uses OpenAI Codex and GPT-4 models to suggest code completions, generate functions from comments, explain existing code, and suggest fixes for test failures — directly in VS Code, JetBrains, Neovim, and more.",
    externalUrl: "https://github.com/features/copilot",
    pricingTier: "freemium",
    pricingNotes: "Free for students/OSS; Individual $10/mo; Business $19/user/mo",
    categoryTags: ["developer tools", "code completion", "ide assistant"],
    industryTags: ["technology", "saas"],
    businessSizeFit: ["solo", "smb", "midmarket", "enterprise"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Context-aware code completion across 20+ programming languages" },
      { text: "Copilot Chat: conversational coding assistant embedded in the IDE" },
      { text: "Fixes test failures automatically with natural language /fix command" },
      { text: "Pull request summaries and code review suggestions on GitHub" },
    ],
    weaknesses: [
      { text: "Suggestions can introduce security vulnerabilities if reviewed carelessly" },
      { text: "Performance degrades on legacy codebases with inconsistent patterns" },
      { text: "Code transmission to GitHub may concern regulated-industry enterprises" },
    ],
    scoreAccuracy: 8.2, scoreLatency: 9.0, scoreReliability: 8.8, scoreEaseOfUse: 9.0, scoreCostEfficiency: 9.0,
    testVersion: "Copilot Enterprise (2024)",
  },
  {
    name: "Cursor",
    vendor: "Anysphere",
    tagline: "AI-first IDE that edits entire files and codebases based on natural language instructions",
    description: "Cursor is a VS Code fork with deep AI integration. Composer mode can make multi-file changes from a single prompt. The codebase indexer gives full project context, enabling AI to refactor across entire modules.",
    externalUrl: "https://cursor.sh",
    pricingTier: "freemium",
    pricingNotes: "Free tier; Pro $20/mo; Business $40/user/mo",
    categoryTags: ["developer tools", "ide", "code generation"],
    industryTags: ["technology"],
    businessSizeFit: ["solo", "smb"],
    integrationTypes: ["native"],
    capabilities: [
      { text: "Composer: multi-file code generation and editing from a single prompt" },
      { text: "Codebase indexing gives full project context for accurate edits" },
      { text: "Tab completion predicts your next edit, not just the next token" },
      { text: "Supports Claude 3.5 Sonnet, GPT-4o, and local Ollama models" },
    ],
    weaknesses: [
      { text: "Large codebase indexing can be slow and occasionally includes stale context" },
      { text: "Sends code to third-party model providers (OpenAI, Anthropic) by default" },
      { text: "Composer edits can miss edge cases in complex multi-module refactors" },
    ],
    scoreAccuracy: 8.5, scoreLatency: 8.8, scoreReliability: 8.0, scoreEaseOfUse: 8.5, scoreCostEfficiency: 8.5,
    testVersion: "0.42",
  },
  {
    name: "Tabnine",
    vendor: "Tabnine",
    tagline: "Privacy-first AI code completion that runs fully on-premise with no data egress",
    description: "Tabnine provides AI code completions with a strong enterprise privacy focus. The on-premise deployment option ensures code never leaves the corporate network. Team learning mode fine-tunes on your private codebase.",
    externalUrl: "https://www.tabnine.com",
    pricingTier: "freemium",
    pricingNotes: "Free basic; Pro $12/mo; Enterprise custom",
    categoryTags: ["developer tools", "code completion"],
    industryTags: ["technology", "financial-services", "healthcare"],
    businessSizeFit: ["solo", "smb", "midmarket", "enterprise"],
    integrationTypes: ["native"],
    capabilities: [
      { text: "On-premise deployment option — code never leaves your network" },
      { text: "Team learning: fine-tunes on your private codebase patterns" },
      { text: "Works fully offline without internet connectivity" },
      { text: "SOC 2 Type II certified for enterprise security compliance" },
    ],
    weaknesses: [
      { text: "Completion quality trails GitHub Copilot in most independent benchmarks" },
      { text: "On-premise deployment requires dedicated GPU infrastructure" },
      { text: "Smaller context window than Copilot reduces codebase awareness" },
    ],
    scoreAccuracy: 7.2, scoreLatency: 8.5, scoreReliability: 8.8, scoreEaseOfUse: 8.0, scoreCostEfficiency: 8.0,
  },
  {
    name: "Devin",
    vendor: "Cognition",
    tagline: "Autonomous AI software engineer that plans, codes, tests, and deploys independently",
    description: "Devin is an autonomous AI software engineer with its own shell, browser, and code editor. It works on long-horizon engineering tasks — writing code, running tests, fixing bugs, and deploying to production without supervision.",
    externalUrl: "https://www.cognition.ai",
    pricingTier: "paid",
    categoryTags: ["developer tools", "autonomous coding", "devops"],
    industryTags: ["technology"],
    businessSizeFit: ["smb", "midmarket", "enterprise"],
    integrationTypes: ["api", "native"],
    capabilities: [
      { text: "Plans multi-step engineering tasks autonomously with self-debugging" },
      { text: "Has its own browser to research docs and Stack Overflow" },
      { text: "Writes code, runs tests, reads errors, and iterates without human input" },
      { text: "Opens pull requests and can deploy to staging environments" },
    ],
    weaknesses: [
      { text: "Success rate on genuinely novel complex tasks is still below 50% in independent evaluations" },
      { text: "Can take unexpected or overly-broad actions if given wide permissions" },
      { text: "Not suitable for security-sensitive production environments without mandatory review gates" },
    ],
    scoreAccuracy: 6.5, scoreLatency: 5.0, scoreReliability: 6.0, scoreEaseOfUse: 7.0, scoreCostEfficiency: 5.5,
  },

  // ── FINANCE & ACCOUNTING ──────────────────────────────────────────────────
  {
    name: "Vic.ai",
    vendor: "Vic.ai",
    tagline: "Autonomous AI accountant that processes invoices and approves payments with no human touch",
    description: "Vic.ai is an autonomous accounting platform. Its AI processes invoices end-to-end: extracts data, matches to POs, routes for approval (or approves autonomously within rules), and posts to your ERP with no human touch.",
    externalUrl: "https://www.vic.ai",
    pricingTier: "paid",
    categoryTags: ["finance", "accounts payable", "invoice processing"],
    industryTags: ["financial-services", "manufacturing", "retail"],
    businessSizeFit: ["midmarket", "enterprise"],
    integrationTypes: ["api", "native"],
    capabilities: [
      { text: "90%+ straight-through processing rate on standard invoice formats" },
      { text: "Autonomous payment approval within pre-configured approval rules" },
      { text: "Integrates with SAP, Oracle, NetSuite, and Microsoft Dynamics 365" },
      { text: "Continuous learning from accountant corrections improves accuracy" },
    ],
    weaknesses: [
      { text: "Accuracy drops significantly on handwritten or non-standard invoice formats" },
      { text: "ERP integration setup takes 8–12 weeks for complex environments" },
      { text: "Not economical for small AP volumes below 1,000 invoices/month" },
    ],
    scoreAccuracy: 8.5, scoreLatency: 8.0, scoreReliability: 8.8, scoreEaseOfUse: 7.0, scoreCostEfficiency: 7.0,
  },
  {
    name: "Brex AI",
    vendor: "Brex",
    tagline: "AI finance assistant that automates expense management, policy enforcement and spend analysis",
    description: "Brex AI is embedded in the Brex spend management platform. It auto-categorises expenses, enforces spend policy in real time before transactions are approved, flags anomalies, and answers natural language spend queries.",
    externalUrl: "https://www.brex.com/platform/ai",
    pricingTier: "freemium",
    categoryTags: ["finance", "expense management", "spend analysis"],
    industryTags: ["technology", "saas"],
    businessSizeFit: ["smb", "midmarket", "enterprise"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Auto-categorises expenses with >95% accuracy against company chart of accounts" },
      { text: "Enforces spend policy before card transactions are approved in real time" },
      { text: "Natural language spend queries: 'Show me SaaS spend by team this quarter'" },
      { text: "Anomaly detection flags unusual spending patterns proactively" },
    ],
    weaknesses: [
      { text: "Only works within Brex card and platform ecosystem — not standalone" },
      { text: "US-centric product — limited multi-currency and international tax compliance" },
      { text: "Full AI coverage requires all employees to use Brex corporate cards" },
    ],
    scoreAccuracy: 8.2, scoreLatency: 8.5, scoreReliability: 8.5, scoreEaseOfUse: 8.8, scoreCostEfficiency: 8.0,
  },

  // ── HR & RECRUITING ───────────────────────────────────────────────────────
  {
    name: "Paradox Olivia",
    vendor: "Paradox",
    tagline: "Conversational AI recruiting assistant that screens, schedules, and onboards candidates 24/7",
    description: "Olivia is Paradox's conversational AI recruiter. She screens candidates via chat, automatically schedules interviews in recruiters' calendars, answers candidate FAQs, and handles offer letter administration — at any hour of the day.",
    externalUrl: "https://www.paradox.ai",
    pricingTier: "enterprise",
    categoryTags: ["hr", "recruiting", "talent acquisition"],
    industryTags: ["retail", "healthcare", "manufacturing"],
    businessSizeFit: ["midmarket", "enterprise"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Screens candidates conversationally 24/7 with consistent evaluation criteria" },
      { text: "Books interviews directly in recruiter and hiring manager calendars" },
      { text: "Handles high-volume hourly hiring workflows at scale" },
      { text: "Multilingual conversations across major global languages" },
    ],
    weaknesses: [
      { text: "Conversational screening can feel impersonal for senior professional roles" },
      { text: "Integration with legacy ATS systems can require custom connector work" },
      { text: "Enterprise pricing is significant — typically not suitable for SMBs" },
    ],
    scoreAccuracy: 7.8, scoreLatency: 8.5, scoreReliability: 8.5, scoreEaseOfUse: 7.5, scoreCostEfficiency: 6.0,
  },
  {
    name: "Moveworks",
    vendor: "Moveworks",
    tagline: "AI employee service agent that resolves IT and HR requests autonomously from Slack or Teams",
    description: "Moveworks is an enterprise AI service agent for IT and HR. Employees ask questions in Slack or Teams and Moveworks autonomously resolves requests: resets passwords, provisions software, answers HR policy questions, and routes complex issues.",
    externalUrl: "https://www.moveworks.com",
    pricingTier: "enterprise",
    categoryTags: ["hr", "it helpdesk", "productivity"],
    industryTags: ["technology", "financial-services", "manufacturing"],
    businessSizeFit: ["enterprise"],
    integrationTypes: ["native", "api", "slack"],
    capabilities: [
      { text: "Resolves IT requests autonomously: password resets, software provisioning" },
      { text: "HR policy Q&A with citations from your employee handbook and policies" },
      { text: "Works natively inside Slack and Microsoft Teams without new app installs" },
      { text: "Semantic understanding resolves the same intent expressed in 1,000 different ways" },
    ],
    weaknesses: [
      { text: "Very expensive — enterprise contracts typically start at $500k+/year" },
      { text: "Implementation takes 3–6 months to integrate with all HR and IT systems" },
      { text: "ROI difficult to justify for organisations under 500 employees" },
    ],
    scoreAccuracy: 8.5, scoreLatency: 8.5, scoreReliability: 9.0, scoreEaseOfUse: 8.0, scoreCostEfficiency: 4.5,
  },

  // ── PRODUCTIVITY ──────────────────────────────────────────────────────────
  {
    name: "Notion AI",
    vendor: "Notion",
    tagline: "AI writing and summarisation assistant embedded in your Notion workspace",
    description: "Notion AI is built into every Notion workspace. It writes first drafts, summarises documents, extracts action items from meeting notes, translates content, and answers questions about your workspace content with citations.",
    externalUrl: "https://www.notion.so/product/ai",
    pricingTier: "freemium",
    pricingNotes: "$10/user/mo add-on on paid Notion plans",
    categoryTags: ["productivity", "writing", "knowledge management"],
    industryTags: ["technology", "media", "consulting"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["native"],
    capabilities: [
      { text: "Summarises long documents into key points with one click" },
      { text: "Extracts action items and decisions from meeting notes automatically" },
      { text: "Writes first drafts and continues writing directly in existing docs" },
      { text: "Q&A over workspace: ask questions, get answers with page citations" },
    ],
    weaknesses: [
      { text: "Q&A quality degrades significantly for large workspaces with poor structure" },
      { text: "Cannot access content outside Notion (emails, Slack, external docs)" },
      { text: "Writing quality is average compared to dedicated AI writing tools" },
    ],
    scoreAccuracy: 7.5, scoreLatency: 8.5, scoreReliability: 8.8, scoreEaseOfUse: 9.5, scoreCostEfficiency: 8.0,
  },
  {
    name: "Microsoft Copilot for M365",
    vendor: "Microsoft",
    tagline: "AI assistant embedded in Word, Excel, Teams, and Outlook that works across all your Microsoft data",
    description: "Microsoft 365 Copilot integrates GPT-4 into the entire Microsoft 365 suite. In Teams it summarises meetings and generates action items. In Excel it creates formulas and analyses data. In Outlook it drafts and summarises emails.",
    externalUrl: "https://www.microsoft.com/en-us/microsoft-365/copilot-for-microsoft-365",
    pricingTier: "enterprise",
    pricingNotes: "$30/user/mo add-on — requires M365 Business Premium or E3/E5",
    categoryTags: ["productivity", "office suite", "meeting assistant"],
    industryTags: ["financial-services", "manufacturing", "healthcare"],
    businessSizeFit: ["midmarket", "enterprise"],
    integrationTypes: ["native"],
    capabilities: [
      { text: "Summarises Teams meetings with action items and follow-up suggestions" },
      { text: "Drafts Word documents from a brief prompt using your organisation's data" },
      { text: "Excel: generates formulas, data analysis, and charts from natural language" },
      { text: "Outlook: summarises long email threads and drafts contextual replies" },
    ],
    weaknesses: [
      { text: "Requires M365 E3/E5 or Business Premium — high total cost per seat" },
      { text: "AI accuracy is inconsistent across different M365 apps (Word > Excel > Teams)" },
      { text: "Copilot can surface documents employees may not be authorised to read" },
    ],
    scoreAccuracy: 7.8, scoreLatency: 7.5, scoreReliability: 8.0, scoreEaseOfUse: 8.5, scoreCostEfficiency: 6.0,
  },
  {
    name: "Otter.ai",
    vendor: "Otter.ai",
    tagline: "AI meeting assistant that transcribes, summarises, and extracts action items in real time",
    description: "Otter.ai joins your Zoom, Teams, or Google Meet calls and transcribes them in real time. It generates meeting summaries with action items and lets teammates ask questions about meeting content post-call.",
    externalUrl: "https://otter.ai",
    pricingTier: "freemium",
    pricingNotes: "Free 600 min/mo; Pro $16.99/mo; Business $30/user/mo",
    categoryTags: ["productivity", "meeting assistant", "transcription"],
    industryTags: ["technology", "consulting", "education"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["native", "zapier"],
    capabilities: [
      { text: "Real-time transcription with automatic speaker identification" },
      { text: "Auto-generated meeting summaries and bulleted action items" },
      { text: "OtterPilot joins scheduled meetings automatically on your behalf" },
      { text: "Chat with Otter AI about meeting content for Q&A post-meeting" },
    ],
    weaknesses: [
      { text: "Transcription accuracy drops significantly with heavy accents or multiple simultaneous speakers" },
      { text: "Free tier has a 600-minute monthly limit that constrains heavy users" },
      { text: "External participants may have privacy objections to being recorded by a bot" },
    ],
    scoreAccuracy: 7.8, scoreLatency: 9.0, scoreReliability: 8.5, scoreEaseOfUse: 9.0, scoreCostEfficiency: 8.5,
  },
  {
    name: "Fireflies.ai",
    vendor: "Fireflies",
    tagline: "AI meeting recorder and assistant that transcribes, summarises, and searches all your calls",
    description: "Fireflies.ai automatically joins and records all your video meetings, transcribes them, and uses AI to generate summaries and action items with a searchable conversation history. Integrates with Salesforce, HubSpot, and Slack.",
    externalUrl: "https://fireflies.ai",
    pricingTier: "freemium",
    pricingNotes: "Free 800 min storage; Pro $18/mo; Business $29/mo",
    categoryTags: ["productivity", "meeting assistant", "transcription"],
    industryTags: ["technology", "consulting", "sales"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["native", "api", "zapier", "slack"],
    capabilities: [
      { text: "Auto-joins and records Zoom, Teams, and Google Meet calls" },
      { text: "Smart search: finds any spoken moment across all past meetings" },
      { text: "Topic trackers: alerts when pre-configured subjects are mentioned" },
      { text: "CRM sync: auto-logs call notes and action items to Salesforce and HubSpot" },
    ],
    weaknesses: [
      { text: "Bot joining calls can feel intrusive for external client participants" },
      { text: "Transcription accuracy is lower than Otter.ai in noisy call environments" },
      { text: "Free storage fills up within 2–3 weeks for frequent meeting participants" },
    ],
    scoreAccuracy: 7.5, scoreLatency: 8.5, scoreReliability: 8.5, scoreEaseOfUse: 8.8, scoreCostEfficiency: 8.5,
  },
  {
    name: "Glean",
    vendor: "Glean",
    tagline: "Enterprise AI search that finds and synthesises information across all your company tools",
    description: "Glean is an enterprise search platform with AI. It indexes every tool in your stack — Slack, Docs, Jira, Confluence, Salesforce — and lets employees find any information with semantic search and an AI assistant that synthesises results.",
    externalUrl: "https://www.glean.com",
    pricingTier: "enterprise",
    categoryTags: ["productivity", "enterprise search", "knowledge management"],
    industryTags: ["technology", "financial-services"],
    businessSizeFit: ["midmarket", "enterprise"],
    integrationTypes: ["api", "native"],
    capabilities: [
      { text: "Indexes 100+ enterprise tools for unified permissions-aware semantic search" },
      { text: "AI assistant answers questions from your company's actual internal data" },
      { text: "Search results respect each user's individual access permissions" },
      { text: "Glean Apps: custom AI workflows built on your company knowledge base" },
    ],
    weaknesses: [
      { text: "Integration setup takes weeks to months for large organisations" },
      { text: "Index freshness can lag for high-velocity tools like Slack" },
      { text: "Typically $15–$30/user/mo — significant budget for large teams" },
    ],
    scoreAccuracy: 8.0, scoreLatency: 8.0, scoreReliability: 8.5, scoreEaseOfUse: 8.5, scoreCostEfficiency: 6.5,
  },

  // ── WRITING & CONTENT ─────────────────────────────────────────────────────
  {
    name: "Grammarly Business",
    vendor: "Grammarly",
    tagline: "AI writing assistant that improves clarity, tone, and correctness across every business app",
    description: "Grammarly Business provides AI-powered writing suggestions across 500,000+ apps via browser extension and API. Business plans add brand tone guidelines, style guides, and snippet templates for consistent communication.",
    externalUrl: "https://www.grammarly.com/business",
    pricingTier: "paid",
    pricingNotes: "Business: $15/user/mo (minimum 3 seats)",
    categoryTags: ["writing", "editing", "grammar"],
    industryTags: ["technology", "financial-services", "healthcare"],
    businessSizeFit: ["solo", "smb", "midmarket", "enterprise"],
    integrationTypes: ["chrome-extension", "api", "native"],
    capabilities: [
      { text: "Context-aware grammar and style corrections in real time across all apps" },
      { text: "Brand tone guidelines enforce consistent voice across team communications" },
      { text: "Works across 500,000+ apps via browser extension with no setup" },
      { text: "GDPR compliant with option to disable AI improvement training" },
    ],
    weaknesses: [
      { text: "Free tier is now very limited — core AI features require paid subscription" },
      { text: "Aggressive in-product upsell prompts interrupt writing flow" },
      { text: "Style suggestions can over-simplify technical or domain-specific writing" },
    ],
    scoreAccuracy: 8.8, scoreLatency: 9.5, scoreReliability: 9.5, scoreEaseOfUse: 9.5, scoreCostEfficiency: 8.5,
  },
  {
    name: "Writer",
    vendor: "Writer",
    tagline: "Enterprise AI platform with brand-safe content generation and workflow automation",
    description: "Writer is an enterprise AI content platform. It trains on your brand guidelines and company knowledge to generate content that is always on-brand. Used by enterprise marketing, comms, and legal teams at scale.",
    externalUrl: "https://writer.com",
    pricingTier: "enterprise",
    pricingNotes: "Team $18/user/mo; Enterprise custom",
    categoryTags: ["writing", "content creation", "enterprise ai"],
    industryTags: ["technology", "financial-services", "healthcare"],
    businessSizeFit: ["midmarket", "enterprise"],
    integrationTypes: ["api", "chrome-extension", "native"],
    capabilities: [
      { text: "Custom model training on your brand guidelines and internal terminology" },
      { text: "Palmyra models: Writer's own LLMs optimised for enterprise content accuracy" },
      { text: "AI guardrails enforce compliance rules and brand standards at generation time" },
      { text: "Pipelines: automated content workflows connected to your business data" },
    ],
    weaknesses: [
      { text: "Custom model fine-tuning requires significant content dataset preparation work" },
      { text: "Teams plan has limited features — full value only available on Enterprise" },
      { text: "Less flexible than general-purpose LLMs for technical or code-related content" },
    ],
    scoreAccuracy: 8.0, scoreLatency: 8.0, scoreReliability: 8.5, scoreEaseOfUse: 8.0, scoreCostEfficiency: 6.5,
  },

  // ── LEGAL ─────────────────────────────────────────────────────────────────
  {
    name: "Harvey",
    vendor: "Harvey AI",
    tagline: "AI legal assistant trained on legal data for contract review, due diligence, and research",
    description: "Harvey is an AI platform built for law firms and in-house legal teams. It is trained on legal precedent and can review contracts, conduct due diligence, draft clauses, and research case law faster than a junior associate.",
    externalUrl: "https://www.harvey.ai",
    pricingTier: "enterprise",
    categoryTags: ["legal", "contract review", "due diligence"],
    industryTags: ["legal", "financial-services"],
    businessSizeFit: ["midmarket", "enterprise"],
    integrationTypes: ["api", "native"],
    capabilities: [
      { text: "Contract review: extracts and flags non-standard and high-risk clauses" },
      { text: "Due diligence: processes thousands of documents in hours instead of weeks" },
      { text: "Legal research: surfaces relevant case law and precedent with citations" },
      { text: "Domain-trained models outperform generic LLMs on legal accuracy benchmarks" },
    ],
    weaknesses: [
      { text: "Significant enterprise pricing — only accessible to large law firms and legal departments" },
      { text: "All output must be reviewed by a qualified attorney before use" },
      { text: "Coverage strongest for US and UK law — other jurisdictions are less well supported" },
    ],
    scoreAccuracy: 8.2, scoreLatency: 7.5, scoreReliability: 8.5, scoreEaseOfUse: 7.5, scoreCostEfficiency: 5.5,
  },
  {
    name: "Spellbook",
    vendor: "Rally Legal",
    tagline: "AI contract drafting and review tool embedded in Microsoft Word",
    description: "Spellbook is an AI contract drafting assistant that works inside Microsoft Word. It reviews entire agreements, suggests missing clauses, provides a risk rating per clause, and drafts new provisions — all without leaving Word.",
    externalUrl: "https://www.spellbook.legal",
    pricingTier: "paid",
    pricingNotes: "Starter $99/mo; Professional $199/mo",
    categoryTags: ["legal", "contract review", "drafting"],
    industryTags: ["legal", "technology", "real-estate"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["native"],
    capabilities: [
      { text: "Reviews contracts and flags unusual or missing clauses directly in Word" },
      { text: "Red/amber/green risk rating for clause-by-clause risk analysis" },
      { text: "Suggests alternative clause language with plain-English explanation" },
      { text: "Works inside Microsoft Word — no disruption to existing workflow" },
    ],
    weaknesses: [
      { text: "Only supports Microsoft Word — no Google Docs integration" },
      { text: "Less capable than Harvey for large-scale institutional due diligence" },
      { text: "All output requires review by a qualified lawyer before execution" },
    ],
    scoreAccuracy: 7.8, scoreLatency: 8.0, scoreReliability: 8.2, scoreEaseOfUse: 8.5, scoreCostEfficiency: 7.5,
  },

  // ── RESEARCH ──────────────────────────────────────────────────────────────
  {
    name: "Perplexity Pro",
    vendor: "Perplexity AI",
    tagline: "AI answer engine with cited, real-time web research for factual Q&A",
    description: "Perplexity is an AI-powered search and research tool that answers questions with cited sources in real time. Pro subscribers get GPT-4 and Claude-powered answers, unlimited follow-ups, and file upload for document analysis.",
    externalUrl: "https://www.perplexity.ai",
    pricingTier: "freemium",
    pricingNotes: "Free tier; Pro $20/mo",
    categoryTags: ["research", "search", "information retrieval"],
    industryTags: ["technology", "consulting", "healthcare"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["api", "chrome-extension"],
    capabilities: [
      { text: "Real-time web research with inline source citations for every claim" },
      { text: "Multi-turn follow-up questions maintain full conversation context" },
      { text: "Document and PDF upload for Q&A against uploaded files" },
      { text: "Spaces: collaborative research rooms with shared memory and files" },
    ],
    weaknesses: [
      { text: "Hallucinations still occur — cited sources do not guarantee claim accuracy" },
      { text: "API access is expensive compared to querying underlying LLM APIs directly" },
      { text: "Not suitable for research on highly sensitive or confidential topics" },
    ],
    scoreAccuracy: 8.0, scoreLatency: 8.5, scoreReliability: 8.5, scoreEaseOfUse: 9.5, scoreCostEfficiency: 8.5,
  },
  {
    name: "Elicit",
    vendor: "Elicit",
    tagline: "AI research assistant that extracts and synthesises findings from academic papers",
    description: "Elicit is designed for academic and scientific research. Upload papers or search a topic, and Elicit extracts key findings, methodology, sample sizes, and limitations from each paper into structured comparison tables.",
    externalUrl: "https://elicit.com",
    pricingTier: "freemium",
    pricingNotes: "Free 5,000 credits/mo; Plus $10/mo",
    categoryTags: ["research", "academic", "literature review"],
    industryTags: ["healthcare", "education", "consulting"],
    businessSizeFit: ["solo", "smb"],
    integrationTypes: ["api"],
    capabilities: [
      { text: "Extracts structured data (findings, sample size, methodology) from academic papers" },
      { text: "Builds evidence comparison tables for systematic literature reviews" },
      { text: "Searches the Semantic Scholar database for relevant papers by topic" },
      { text: "Summarises papers with key claims highlighted and limitations noted" },
    ],
    weaknesses: [
      { text: "Limited to published academic papers — poor on grey literature and reports" },
      { text: "Extraction accuracy varies by academic discipline (strongest for medicine and biology)" },
      { text: "Cannot access paywalled papers — requires manual PDF upload" },
    ],
    scoreAccuracy: 7.8, scoreLatency: 7.5, scoreReliability: 8.0, scoreEaseOfUse: 8.5, scoreCostEfficiency: 9.0,
  },

  // ── AUTOMATION & INTEGRATION ───────────────────────────────────────────────
  {
    name: "Zapier AI",
    vendor: "Zapier",
    tagline: "AI actions and chatbots on top of the world's most popular automation platform",
    description: "Zapier AI adds LLM-powered steps and chatbot building (Interfaces) to Zapier's automation platform. Users can build AI Zaps that classify emails, extract data, generate summaries, or route tasks across 6,000+ apps.",
    externalUrl: "https://zapier.com/ai",
    pricingTier: "freemium",
    pricingNotes: "Free 100 tasks/mo; Starter $19.99/mo; Professional $49/mo",
    categoryTags: ["automation", "integration", "workflow"],
    industryTags: ["technology", "e-commerce", "marketing"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Connects 6,000+ apps — the widest integration library in automation" },
      { text: "AI by Zapier: LLM step for text extraction and generation in any Zap" },
      { text: "Canvas: visual AI workflow builder with natural language intent parsing" },
      { text: "Interfaces: build internal chatbots connected to your app data" },
    ],
    weaknesses: [
      { text: "Pricing scales quickly at high task volumes — enterprise plans are expensive" },
      { text: "AI steps have limited LLM model options and constrained prompt customisation" },
      { text: "Less capable error recovery than Make.com for complex multi-step workflows" },
    ],
    scoreAccuracy: 7.2, scoreLatency: 7.5, scoreReliability: 8.5, scoreEaseOfUse: 9.0, scoreCostEfficiency: 7.5,
  },
  {
    name: "Bardeen",
    vendor: "Bardeen",
    tagline: "No-code AI automation agent for repetitive browser tasks and research workflows",
    description: "Bardeen is a browser-based automation platform with AI. Users build automations (playbooks) that scrape web data, trigger actions in connected tools, and run multi-step browser workflows — no code required.",
    externalUrl: "https://www.bardeen.ai",
    pricingTier: "freemium",
    pricingNotes: "Free 500 credits; Pro $10/mo; Business $20/mo",
    categoryTags: ["automation", "productivity", "web scraping"],
    industryTags: ["technology", "sales", "recruiting"],
    businessSizeFit: ["solo", "smb"],
    integrationTypes: ["chrome-extension", "native", "api"],
    capabilities: [
      { text: "Automates multi-step browser workflows entirely without code" },
      { text: "Scrapes and structures web data on demand from any website" },
      { text: "Magic Box: describe a workflow in English, Bardeen builds the automation" },
      { text: "500+ pre-built playbooks for common sales and research use cases" },
    ],
    weaknesses: [
      { text: "Browser automations break when target websites change their HTML structure" },
      { text: "Complex conditional logic requires awkward workarounds without coding" },
      { text: "Only runs while the browser is open — no background or server-side execution" },
    ],
    scoreAccuracy: 7.0, scoreLatency: 7.5, scoreReliability: 6.5, scoreEaseOfUse: 8.5, scoreCostEfficiency: 9.0,
  },

  // ── AI FOUNDATION MODELS ──────────────────────────────────────────────────
  {
    name: "Anthropic Claude API",
    vendor: "Anthropic",
    tagline: "Safety-focused AI API with 200k context window for complex reasoning and document analysis",
    description: "Claude API provides access to Anthropic's Claude model family. Claude 3.5 Sonnet leads coding, analysis, and instruction-following benchmarks. The 200k token context window handles entire codebases or legal contracts in a single call.",
    externalUrl: "https://www.anthropic.com/api",
    pricingTier: "paid",
    pricingNotes: "Haiku $0.25/M tokens; Sonnet $3/M; Opus $15/M input",
    categoryTags: ["developer tools", "llm api", "ai foundation model"],
    industryTags: ["technology"],
    businessSizeFit: ["solo", "smb", "midmarket", "enterprise"],
    integrationTypes: ["api"],
    capabilities: [
      { text: "200k token context window handles entire codebases and long documents" },
      { text: "Leads coding benchmarks (SWE-bench) with Claude 3.5 Sonnet" },
      { text: "Constitutional AI training for reduced harmful and biased output" },
      { text: "Computer Use beta: autonomously controls computer interfaces" },
    ],
    weaknesses: [
      { text: "No native image or audio generation capabilities — text and vision input only" },
      { text: "Rate limits can restrict high-throughput production applications on starter tiers" },
      { text: "Haiku model has significantly lower accuracy than Sonnet for complex tasks" },
    ],
    scoreAccuracy: 9.2, scoreLatency: 8.0, scoreReliability: 9.0, scoreEaseOfUse: 8.5, scoreCostEfficiency: 8.0,
    testVersion: "Claude 3.5 Sonnet (Oct 2024)",
  },
  {
    name: "OpenAI GPT-4o API",
    vendor: "OpenAI",
    tagline: "Multimodal AI API supporting text, vision, and audio with fastest response times",
    description: "GPT-4o is OpenAI's flagship multimodal model — the first to process text, images, and audio natively in a single call. The API powers millions of production applications and has the strongest third-party integration ecosystem.",
    externalUrl: "https://platform.openai.com",
    pricingTier: "paid",
    pricingNotes: "GPT-4o: $5/M input tokens; GPT-4o mini: $0.15/M input",
    categoryTags: ["developer tools", "llm api", "ai foundation model"],
    industryTags: ["technology"],
    businessSizeFit: ["solo", "smb", "midmarket", "enterprise"],
    integrationTypes: ["api"],
    capabilities: [
      { text: "Multimodal: processes text, images, and audio natively in one API call" },
      { text: "Function calling enables deterministic structured JSON outputs for agentic apps" },
      { text: "Assistants API provides managed threads, files, code interpreter, and tool use" },
      { text: "Largest third-party plugin and integration ecosystem of any AI model" },
    ],
    weaknesses: [
      { text: "Inconsistent response latency under high API load during peak periods" },
      { text: "128k context window is smaller than Claude's 200k for long document work" },
      { text: "Data usage policy concerns for regulated industry users without Enterprise tier" },
    ],
    scoreAccuracy: 9.0, scoreLatency: 8.5, scoreReliability: 8.8, scoreEaseOfUse: 9.0, scoreCostEfficiency: 8.5,
    testVersion: "GPT-4o (Nov 2024)",
  },

  // ── CONTENT CREATION ──────────────────────────────────────────────────────
  {
    name: "Midjourney",
    vendor: "Midjourney",
    tagline: "AI image generator producing photorealistic and artistic images from text prompts",
    description: "Midjourney is an AI image generation service accessed via Discord or their web app. It produces industry-leading photorealistic and artistic images from text prompts, used by designers, marketers, and creatives worldwide.",
    externalUrl: "https://www.midjourney.com",
    pricingTier: "paid",
    pricingNotes: "Basic $10/mo; Standard $30/mo; Pro $60/mo",
    categoryTags: ["marketing", "design", "image generation"],
    industryTags: ["media", "e-commerce", "gaming"],
    businessSizeFit: ["solo", "smb"],
    integrationTypes: ["api", "native"],
    capabilities: [
      { text: "Industry-leading photorealistic image quality at v6" },
      { text: "Strong aesthetic consistency across a project or visual series" },
      { text: "Style references: generate images matching an existing visual" },
      { text: "Character consistency across multiple separately-generated images" },
    ],
    weaknesses: [
      { text: "Discord-based access is awkward for professional design workflows" },
      { text: "No official API for programmatic image generation in production pipelines" },
      { text: "Text rendering in images remains a common and frustrating failure mode" },
      { text: "Copyright status of training data is disputed in ongoing litigation" },
    ],
    scoreAccuracy: 9.0, scoreLatency: 7.0, scoreReliability: 8.5, scoreEaseOfUse: 7.0, scoreCostEfficiency: 8.0,
  },
  {
    name: "ElevenLabs",
    vendor: "ElevenLabs",
    tagline: "AI voice generation and cloning platform for lifelike speech synthesis and audio content",
    description: "ElevenLabs generates human-quality speech from text in 32+ languages. Voice Cloning creates a custom voice from 1 minute of audio. Used for podcasts, video voiceovers, audiobooks, and conversational voice interfaces.",
    externalUrl: "https://elevenlabs.io",
    pricingTier: "freemium",
    pricingNotes: "Free 10k chars/mo; Starter $5/mo; Creator $22/mo",
    categoryTags: ["content creation", "audio", "voice ai"],
    industryTags: ["media", "e-learning", "gaming"],
    businessSizeFit: ["solo", "smb", "midmarket"],
    integrationTypes: ["api", "native"],
    capabilities: [
      { text: "Market-leading natural speech synthesis quality as of 2024" },
      { text: "Instant voice cloning from as little as 1 minute of audio" },
      { text: "32+ languages with native accent quality per language" },
      { text: "Emotion and prosody control for more expressive generated speech" },
    ],
    weaknesses: [
      { text: "Voice cloning capability has significant misuse potential for deepfake audio" },
      { text: "API latency spikes during peak periods due to compute demand" },
      { text: "Character-based credit pricing is difficult to predict for variable-length content" },
    ],
    scoreAccuracy: 9.2, scoreLatency: 7.5, scoreReliability: 8.2, scoreEaseOfUse: 9.0, scoreCostEfficiency: 8.5,
  },
  {
    name: "Descript",
    vendor: "Descript",
    tagline: "AI-powered video and podcast editor that lets you edit media by editing a transcript",
    description: "Descript transcribes audio and video and lets you edit the media by editing the text transcript. Delete filler words, overdub mistakes with AI voice cloning, remove silences automatically, and publish to podcast platforms in one workflow.",
    externalUrl: "https://www.descript.com",
    pricingTier: "freemium",
    pricingNotes: "Free 1hr/mo; Creator $24/mo; Business $40/mo",
    categoryTags: ["content creation", "video editing", "podcast"],
    industryTags: ["media", "marketing", "e-learning"],
    businessSizeFit: ["solo", "smb"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Edit video by deleting words and sentences from the text transcript" },
      { text: "Overdub: re-record mistakes with an AI voice clone of the original speaker" },
      { text: "One-click removal of all filler words ('um', 'uh', 'like') across recording" },
      { text: "Studio Sound: AI background noise removal and voice clarity enhancement" },
    ],
    weaknesses: [
      { text: "Transcription accuracy drops for non-native English speakers and strong accents" },
      { text: "Overdub voice clone quality degrades noticeably over long-form content" },
      { text: "Performance issues occur with videos longer than 60 minutes in the browser" },
    ],
    scoreAccuracy: 8.0, scoreLatency: 7.5, scoreReliability: 7.8, scoreEaseOfUse: 9.0, scoreCostEfficiency: 8.5,
  },
  {
    name: "Gamma",
    vendor: "Gamma",
    tagline: "AI presentation creator that generates polished decks from a simple prompt or outline",
    description: "Gamma generates fully designed presentations, documents, and websites from a topic or brief outline. AI creates the structure, writes the content, and applies professional layouts — producing a shareable deck in under 2 minutes.",
    externalUrl: "https://gamma.app",
    pricingTier: "freemium",
    pricingNotes: "Free 400 AI credits; Plus $10/mo; Pro $20/mo",
    categoryTags: ["productivity", "presentations", "content creation"],
    industryTags: ["technology", "consulting", "education"],
    businessSizeFit: ["solo", "smb"],
    integrationTypes: ["native"],
    capabilities: [
      { text: "Generates complete polished presentations from a brief prompt in under 2 minutes" },
      { text: "Integrated AI image generation for on-brand visual slides" },
      { text: "Real-time collaboration on AI-generated decks with comments" },
      { text: "Export to PowerPoint or PDF for existing workflow compatibility" },
    ],
    weaknesses: [
      { text: "AI fills slides with plausible-sounding content — factual accuracy requires human review" },
      { text: "Design customisation is limited compared to PowerPoint or Keynote" },
      { text: "Not suitable for data-heavy or detailed technical presentations" },
    ],
    scoreAccuracy: 7.0, scoreLatency: 8.5, scoreReliability: 8.0, scoreEaseOfUse: 9.5, scoreCostEfficiency: 9.0,
  },
  {
    name: "Lindy",
    vendor: "Lindy",
    tagline: "Personal AI assistant that handles email, calendar, and task management autonomously",
    description: "Lindy is a personal AI assistant that connects to your inbox, calendar, Slack, and CRM. It can reply to emails, schedule meetings, qualify leads, and summarise information — all triggered by rules you set in plain English.",
    externalUrl: "https://www.lindy.ai",
    pricingTier: "freemium",
    pricingNotes: "Free 400 tasks/mo; Pro $49.99/mo",
    categoryTags: ["productivity", "automation", "email management"],
    industryTags: ["technology", "consulting", "sales"],
    businessSizeFit: ["solo", "smb"],
    integrationTypes: ["native", "api"],
    capabilities: [
      { text: "Reads and replies to emails autonomously based on your defined rules" },
      { text: "Schedules meetings from natural language email requests without back-and-forth" },
      { text: "Lindies: shareable reusable mini-agents for specific recurring task types" },
      { text: "CRM enrichment: auto-researches prospects and updates records" },
    ],
    weaknesses: [
      { text: "Autonomous email replies risk tone mismatches in sensitive or nuanced conversations" },
      { text: "Requires significant setup time to achieve reliable consistent behaviour" },
      { text: "Execution accuracy for complex multi-step instructions varies considerably" },
    ],
    scoreAccuracy: 7.5, scoreLatency: 8.0, scoreReliability: 7.5, scoreEaseOfUse: 8.0, scoreCostEfficiency: 8.5,
  },
  {
    name: "Pinecone",
    vendor: "Pinecone",
    tagline: "Fully managed vector database purpose-built for AI and semantic search applications",
    description: "Pinecone is a cloud-native vector database for storing and querying AI embeddings. It powers semantic search, recommendation systems, and RAG applications at any scale with millisecond query times.",
    externalUrl: "https://www.pinecone.io",
    pricingTier: "freemium",
    pricingNotes: "Free 1 index; Starter $70/mo; Standard from $0.096/hr",
    categoryTags: ["developer tools", "database", "search"],
    industryTags: ["technology"],
    businessSizeFit: ["solo", "smb", "midmarket", "enterprise"],
    integrationTypes: ["api"],
    capabilities: [
      { text: "Millisecond vector similarity search at billion-vector scale" },
      { text: "Fully managed — no infrastructure management or scaling required" },
      { text: "Namespaces provide multi-tenant data isolation in a single index" },
      { text: "Hybrid search: combines dense vector and sparse keyword search" },
    ],
    weaknesses: [
      { text: "Expensive at scale compared to self-hosted alternatives like pgvector or Weaviate" },
      { text: "Vendor lock-in — migrating to a different vector store is costly and time-consuming" },
      { text: "Metadata filtering has historically had payload size limitations" },
    ],
    scoreAccuracy: 9.0, scoreLatency: 9.5, scoreReliability: 9.5, scoreEaseOfUse: 8.5, scoreCostEfficiency: 6.5,
  },
  {
    name: "Rasa",
    vendor: "Rasa",
    tagline: "Open-source conversational AI platform for building custom enterprise chatbots",
    description: "Rasa is an open-source framework for building conversational AI assistants. It gives enterprises full control over their NLP pipeline, dialogue management, and deployment. No vendor lock-in — runs entirely on your own infrastructure.",
    externalUrl: "https://rasa.com",
    pricingTier: "freemium",
    pricingNotes: "Open source free; Rasa Pro enterprise pricing on request",
    categoryTags: ["customer support", "chatbot", "developer tools"],
    industryTags: ["financial-services", "healthcare", "technology"],
    businessSizeFit: ["midmarket", "enterprise"],
    integrationTypes: ["api", "native"],
    capabilities: [
      { text: "Full NLP pipeline control: NER, intent classification, entity extraction" },
      { text: "On-premise deployment — conversation data never leaves your infrastructure" },
      { text: "Rasa Pro adds enterprise RBAC, SSO, analytics, and dedicated support" },
      { text: "Large open-source community with reusable dialogue components and connectors" },
    ],
    weaknesses: [
      { text: "Requires ML engineering expertise to build, train, and maintain pipelines" },
      { text: "Significantly higher development effort than no-code chatbot alternatives" },
      { text: "Open-source version has limited support — issues often resolved via community forums" },
    ],
    scoreAccuracy: 7.0, scoreLatency: 8.5, scoreReliability: 7.5, scoreEaseOfUse: 4.0, scoreCostEfficiency: 8.5,
  },
  {
    name: "Cohere Rerank",
    vendor: "Cohere",
    tagline: "AI reranking API that dramatically improves search relevance for enterprise search systems",
    description: "Cohere Rerank takes a search query and a list of candidate documents and reorders them by semantic relevance. It drops into existing search infrastructure (Elasticsearch, OpenSearch) to improve result quality without rebuilding the stack.",
    externalUrl: "https://cohere.com/rerank",
    pricingTier: "paid",
    pricingNotes: "$2 per 1,000 search queries",
    categoryTags: ["developer tools", "search", "enterprise ai"],
    industryTags: ["technology", "e-commerce"],
    businessSizeFit: ["smb", "midmarket", "enterprise"],
    integrationTypes: ["api"],
    capabilities: [
      { text: "Reranks search candidate results by semantic relevance in under 100ms" },
      { text: "Multilingual support across 100+ languages from a single model" },
      { text: "Drops into existing Elasticsearch and OpenSearch deployments" },
      { text: "Significantly outperforms BM25 keyword ranking on semantic and long-tail queries" },
    ],
    weaknesses: [
      { text: "API-only — requires developer integration work to add to existing search stack" },
      { text: "Per-query pricing becomes expensive for very high search volumes" },
      { text: "Only improves ranking of existing candidate results — does not retrieve or generate content" },
    ],
    scoreAccuracy: 8.8, scoreLatency: 9.0, scoreReliability: 9.5, scoreEaseOfUse: 7.5, scoreCostEfficiency: 8.0,
  },
  {
    name: "Superhuman AI",
    vendor: "Superhuman",
    tagline: "AI-powered email client that writes, prioritises, and summarises email threads instantly",
    description: "Superhuman is the fastest email client with deep AI integration. AI auto-summarises long threads, drafts replies in your personal voice, instantly identifies emails needing action, and splits your inbox by priority and sender type.",
    externalUrl: "https://superhuman.com",
    pricingTier: "paid",
    pricingNotes: "$30/user/mo — Gmail and Outlook only",
    categoryTags: ["productivity", "email management", "writing"],
    industryTags: ["technology", "consulting", "venture"],
    businessSizeFit: ["solo", "smb"],
    integrationTypes: ["native"],
    capabilities: [
      { text: "Instant thread summaries eliminate need to read long email chains" },
      { text: "AI drafts full emails in your personal voice from a 2-word prompt" },
      { text: "Priority inbox: AI separates high-value emails from low-priority noise" },
      { text: "Keyboard-driven workflow with the fastest email client latency available" },
    ],
    weaknesses: [
      { text: "$30/mo is expensive for a product limited to a single app category" },
      { text: "Only supports Gmail and Outlook — no other email providers" },
      { text: "Required onboarding call prevents immediate self-serve access" },
    ],
    scoreAccuracy: 8.5, scoreLatency: 9.5, scoreReliability: 9.0, scoreEaseOfUse: 8.5, scoreCostEfficiency: 6.5,
  },
  {
    name: "Chatbase",
    vendor: "Chatbase",
    tagline: "No-code chatbot builder that creates a custom ChatGPT trained on your own data",
    description: "Chatbase lets you build a custom AI chatbot by uploading your docs, website URL, or Notion pages. The chatbot can be embedded on your website or integrated via API to handle customer Q&A from your knowledge base.",
    externalUrl: "https://www.chatbase.co",
    pricingTier: "freemium",
    pricingNotes: "Free 1 chatbot; Hobby $19/mo; Standard $99/mo",
    categoryTags: ["customer support", "chatbot", "knowledge base"],
    industryTags: ["saas", "e-commerce", "education"],
    businessSizeFit: ["solo", "smb"],
    integrationTypes: ["api", "native"],
    capabilities: [
      { text: "Custom chatbot trained on your documents, website, and PDFs in minutes" },
      { text: "Multiple data source ingestion: uploaded files, URLs, and Notion pages" },
      { text: "Website embed with a single line of code — no development required" },
      { text: "API access for building custom integrations and workflows" },
    ],
    weaknesses: [
      { text: "Q&A accuracy drops when context is ambiguous or knowledge base has gaps" },
      { text: "Limited conversation flow customisation versus dedicated chatbot platforms" },
      { text: "Live handoff to human agents only available on Standard plan and above" },
    ],
    scoreAccuracy: 7.2, scoreLatency: 8.5, scoreReliability: 8.0, scoreEaseOfUse: 9.5, scoreCostEfficiency: 8.5,
  },
]

async function main() {
  console.log(`🌱 Seeding ${AGENTS.length} agents…\n`)

  let created = 0
  let skipped = 0

  for (const agent of AGENTS) {
    // Check if already exists (idempotent by name+vendor)
    const existing = await db.agent.findFirst({
      where: { name: agent.name, vendor: agent.vendor },
    })
    if (existing) {
      console.log(`  ⟳ Skip (exists): ${agent.name}`)
      skipped++
      continue
    }

    try {
      await db.agent.create({
        data: {
          name: agent.name,
          vendor: agent.vendor,
          tagline: agent.tagline,
          description: agent.description,
          externalUrl: agent.externalUrl,
          pricingTier: agent.pricingTier,
          pricingNotes: agent.pricingNotes,
          categoryTags: agent.categoryTags,
          industryTags: agent.industryTags,
          businessSizeFit: agent.businessSizeFit,
          integrationTypes: agent.integrationTypes,
          capabilities: agent.capabilities,
          weaknesses: agent.weaknesses, // editorial invariant: always non-empty
          scoreAccuracy: agent.scoreAccuracy ?? null,
          scoreLatency: agent.scoreLatency ?? null,
          scoreReliability: agent.scoreReliability ?? null,
          scoreEaseOfUse: agent.scoreEaseOfUse ?? null,
          scoreCostEfficiency: agent.scoreCostEfficiency ?? null,
          testVersion: agent.testVersion ?? null,
          status: "active",
        },
      })
      created++
      console.log(`  ✓ ${agent.name} (${agent.vendor})`)
    } catch (err) {
      console.error(`  ✗ ${agent.name}: ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  console.log(`\n✅ Done: ${created} created, ${skipped} skipped`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
